### ISSUE TITLE
Please enter a lisence

### ISSUE THREAD

**Issue by Artem13327** [Osanosa/ThemedManager#1]

**Comment by Osanosa** [comment]
Whatcha talking about

**Comment by Osanosa** [comment]
Ok but why would you need that

**Comment by Osanosa** [comment]
I'm just curious, you can contact me on telegram and discuss your plans on this repository or just write em here

**Comment by Osanosa** [comment]
Also I suggest that you speak Russian and is so you're free to use it to talk

**Comment by Osanosa** [comment]
t.me/osanosa личный
t.me/themedsupport группа поддержки
